- name: Home change
  hosts: "{{host_name}}"
  gather_facts: no
## Bu play patchlenmiş oracle home ile patchlenmemiş oracle home'un yerini değiştirir ve runInstaller çalıştırır.
  tasks:
## {{ORACLE_HOME}}.old kontrolu yapar
  - name: check if {{ORACLE_HOME}}.old exists
    stat:
       path: "{{ORACLE_HOME}}.old"
    register: file_exists
## {{ORACLE_HOME}}.old varsa işin yarıda kesildiğini düşünüp play'i sonlandırır.
  - name: Fail if {{ORACLE_HOME}}.old exist
    fail:
      msg: "There is {{ORACLE_HOME}}.old, check server"
    when: file_exists.stat.exists
## patchlenmiş home ile patchlenmemiş home'un yerini değiştirir, boş bir oraInventory create eder (runInstaller için)
  - name: Create new directory
    become: yes
    become_user: oracle
    command: "{{ item }}"
    loop:
      - mv /oracle/oraInventory /oracle/oraInventory.old
      - mkdir -p /oracle/oraInventory
      - mv {{ORACLE_HOME}} {{ORACLE_HOME}}.old
      - mv {{ORACLE_HOME}}.new {{ORACLE_HOME}}
## oracle profile'ı yükler. Home_kurulum.sh'i çalıştırır.
  - name: set db profiles
    become: yes
    become_user: oracle
    shell: |
       . ~oracle/.profile
       sh {{ORACLE_HOME}}/home_kurulum.sh
    args:
      executable: /bin/bash
    register: software_result
    ignore_errors: True
##sh'in sonucuna göre play'i keser ya da devam eder.
  - name: check success or not
    debug:
     msg: "software installation is succeed"
    when: software_result.stdout_lines is search("Successfully")

  - name: check success or not
    fail:
     msg: "software installation is not succeed"
    when: software_result.stdout_lines is not search("Successfully")
